/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}_rand31pmc_next"]
    pub fn rand31pmc_next() -> ::std::os::raw::c_ulong;
}
extern "C" {
    #[link_name = "\u{1}_rand31pmc_seedi"]
    pub fn rand31pmc_seedi(arg1: ::std::os::raw::c_ulong);
}
extern "C" {
    #[link_name = "\u{1}_rand31pmc_ranlui"]
    pub fn rand31pmc_ranlui() -> ::std::os::raw::c_ulong;
}
extern "C" {
    #[link_name = "\u{1}_rand31pmc_ranf"]
    pub fn rand31pmc_ranf() -> f32;
}
pub const seed31pmc: ::std::os::raw::c_ulong = 1;
